project:
  type: website

website:
  title: "UQRUG"   
  image: "uqrug_preview.png"
  favicon: "uqrug_fav.png"  
  navbar:
    logo: "uqrug.png"
    background: "#48206c"  
    foreground: "white" 
    right: 
      - events.qmd
      - icon: github
        href: https://github.com/uqlibrary/technology-training
        aria-label: github
      - icon: twitter
        href: https://twitter.com/UQ_RUG
        aria-label: Twitter 
      - icon: file-earmark-text
        href: https://frama.link/uqrug 
        aria-label: Collaborative Document
      - icon: chat-right
        href: https://chat.uq.edu.au/element/#/room/#uqrug:chat.uq.edu.au
        aria-label: UQ Chat 
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

